### ISSUE TITLE
updateopenflixr attempts to replace nginx.conf

### ISSUE THREAD

**Issue by jeremysherriff** [mfrelink/OpenFLIXR2.OnlineUpdate#10]
During first run of `sudo updateopenflixr`, the script prompts for remediation of nginx.conf:
![image](https://user-images.githubusercontent.com/1082213/47986369-68ab9800-e141-11e8-9721-04ba014da3cb.png)

I believe this script is intended to run unattended.
Depending on response, the same will occur on all `updatewkly.sh` runs.

**Comment by jeremysherriff** [comment]
Same happens with vmware-tools/tools.conf (much less important):
![image](https://user-images.githubusercontent.com/1082213/47986542-ef607500-e141-11e8-80cc-bc7c61a22e44.png)

**Comment by mfrelink** [comment]
This should be fixed in 2.9 but I can only be 100% positive after release and testing.

**Comment by mfrelink** [comment]
Fixed in 2.9
