### ISSUE TITLE
nginx ssl directive problem on first updateopenflixr run

### ISSUE THREAD

**Issue by jeremysherriff** [mfrelink/OpenFLIXR2.OnlineUpdate#11]
The nginx configuration is invalid during the first run-though of `sudo updateopenflixr`.  Although there is logic in the update scripts to correct this, the issue is encountered before the OF scripts have corrected the configuration. This leaves a fresh install of OF in an unusable state, in an apt-get loop with nginx stopped.

**Comment by mfrelink** [comment]
Fixed in 2.9
