### ISSUE TITLE
SickRage git repo hijack

### ISSUE THREAD

**Issue by jeremysherriff** [mfrelink/OpenFLIXR2.OnlineUpdate#6]
SickRage's github repo has been hijacked after a trademark dispute (see https://github.com/SickChill/SickChill/blob/master/readme.md).

OpenFlixr will need the base repo for sickchill updating and potentially some dependencies to be fixed after the original sickrage repo cause dependency chains to be broken.

**Comment by mfrelink** [comment]
Fixed in 2.8
