### ISSUE TITLE
updateopenflixr script requires input

### ISSUE THREAD

**Issue by jeremysherriff** [mfrelink/OpenFLIXR2.OnlineUpdate#8]
A fresh install of OF from the `2.0` download and runnin g`sudo updateopenflixr` as per instructions.  After the download of all outstanding Ubuntu Xenial updates, the package installer prompts for remediation of `/etc/issues`.  I believe this script is intended to be unattended.

**Comment by mfrelink** [comment]
This should be fixed in 2.9 but I can only be 100% positive after release and testing.

**Comment by mfrelink** [comment]
Fixed in 2.9
