### ISSUE TITLE
Initial run updateopenflixr exhausts all memory in default configuration

### ISSUE THREAD

**Issue by jeremysherriff** [mfrelink/OpenFLIXR2.OnlineUpdate#9]
Using a default hardware configuration (3GB RAM, 2 vCPU) the initial run of `sudo updateopenflixr` exhausts all memory and the system becomes non-responsive.  This may be due to the large number of updates to be worked through during the `configure` stage of the first `apt-get upgrade` run - for me, the system ran out of RAM while compiling updated versions of mono libraries.

This broke apt and required triage to resolve:
![image](https://user-images.githubusercontent.com/1082213/47986022-4feeb280-e140-11e8-9274-6bd79ca421b2.png)

**Comment by mfrelink** [comment]
Fixed in 2.9
